CREATE SCHEMA IF NOT EXISTS Ejercicio3 ;
USE Ejercicio3 ;
-- -----------------------------------------------------
-- Table Ejercicio3.SOCIOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ejercicio3.SOCIOS (
idPERSONA INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
APELLIDO VARCHAR(45) NOT NULL,
TELEFONO INT NOT NULL,
DIRECCION VARCHAR(45) NOT NULL,
PRIMARY KEY (idPERSONA))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table Ejercicio3.BARCOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ejercicio3.BARCOS (
idBARCOS INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
NUMEROAMARRE INT NOT NULL,
CUOTA INT NOT NULL,
SOCIOS_idPERSONA INT NOT NULL,
PRIMARY KEY (idBARCOS),
INDEX fk_BARCOS_SOCIOS_idx (SOCIOS_idPERSONA ASC) VISIBLE,
CONSTRAINT fk_BARCOS_SOCIOS
FOREIGN KEY (SOCIOS_idPERSONA)
REFERENCES Ejercicio3.SOCIOS (idPERSONA)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table Ejercicio3.SALIDAS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ejercicio3.SALIDAS (
idMEDICO INT NOT NULL AUTO_INCREMENT,
FECHASALIDA DATE NOT NULL,
HORASALIDA TIME NOT NULL,
DESTINO VARCHAR(45) NOT NULL,
PRIMARY KEY (idMEDICO))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table Ejercicio3.PATRON
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ejercicio3.PATRON (
idCEDULA INT NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
APELLIDO VARCHAR(45) NOT NULL,
EDAD INT NOT NULL,
FECHANACIMIENTO DATE NOT NULL,
DIRECCION VARCHAR(45) NOT NULL,
BARCOS_idBARCOS INT NOT NULL,
PRIMARY KEY (idCEDULA),
INDEX fk_PATRON_BARCOS1_idx (BARCOS_idBARCOS ASC) VISIBLE,
CONSTRAINT fk_PATRON_BARCOS1
FOREIGN KEY (BARCOS_idBARCOS)
REFERENCES Ejercicio3.BARCOS (idBARCOS)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table Ejercicio3.SALIDAS_has_BARCOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Ejercicio3.SALIDAS_has_BARCOS (
SALIDAS_idMEDICO INT NOT NULL,
BARCOS_idBARCOS INT NOT NULL,
PRIMARY KEY (SALIDAS_idMEDICO, BARCOS_idBARCOS),
INDEX fk_SALIDAS_has_BARCOS_BARCOS1_idx (BARCOS_idBARCOS ASC) VISIBLE,
INDEX fk_SALIDAS_has_BARCOS_SALIDAS1_idx (SALIDAS_idMEDICO ASC) VISIBLE,
CONSTRAINT fk_SALIDAS_has_BARCOS_SALIDAS1
FOREIGN KEY (SALIDAS_idMEDICO)
REFERENCES Ejercicio3.SALIDAS (idMEDICO)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT fk_SALIDAS_has_BARCOS_BARCOS1
FOREIGN KEY (BARCOS_idBARCOS)
REFERENCES Ejercicio3.BARCOS (idBARCOS)
ON DELETE NO ACTION
ON UPDATE NO ACTION)
ENGINE = InnoDB;